const form = {
  formId: 'new-user-form',
  formField: {
    patientID: {
      name: 'patientID',
      label: 'Patient ID',
      type: 'text',
      errorMsg: 'Patient ID is required.',
      default: '123456',
    },
    firstName: {
      name: 'firstName',
      label: 'First Name',
      type: 'text',
      errorMsg: 'First name is required.',
      default: 'John',
    },
    lastName: {
      name: 'lastName',
      label: 'Last Name',
      type: 'text',
      errorMsg: 'Last name is required.',
      default: 'Doe',
    },
    weight: {
      name: 'weight',
      label: 'Weight',
      type: 'text',
      errorMsg: 'Weight is required.',
      default: '95 kg',
    },
    height: {
      name: 'height',
      label: 'Height',
      type: 'text',
      errorMsg: 'Height is required.',
      default: '180 cm',
    },
    dateOfBirth: {
      name: 'dateOfBirth',
      label: 'Date of Birth',
      type: 'date',
      errorMsg: 'Date of birth is required',
      default: '1990-01-01',
    },
    email: {
      name: 'email',
      label: 'Email',
      type: 'email',
      errorMsg: 'Email is required',
      default: 'johndoe@example.com',
    },
    sex: {
      name: 'sex',
      label: 'Sex',
      type: 'text',
      errorMsg: 'Sex is required',
      default: 'Male',
    },
    phone: {
      name: 'phone',
      label: 'Phone',
      type: 'text',
      errorMsg: 'Phone is required',
      default: '123-456-7890',
    },
    emergencyContact: {
      name: 'emergencyContact',
      label: 'Emergency Contact',
      type: 'text',
      errorMsg: 'Emergency Contact is required',
      default: 'Jane Doe',
    },
    emergencyPhone: {
      name: 'emergencyPhone',
      label: 'Emergency Phone',
      type: 'text',
      errorMsg: 'Emergency Phone is required',
      default: '098-765-4321',
    },
    insuranceInformation: {
      name: 'insuranceInformation',
      label: 'Insurance Information',
      type: 'text',
      errorMsg: 'Insurance Information is required',
      default: 'Provider X - Policy 1234',
    },
    previousDiagnoses: {
      name: 'previousDiagnoses',
      label: 'Previous Diagnoses',
      type: 'text',
      errorMsg: 'Previous Diagnoses is required',
      default: 'None',
    },
    pastSurgeries: {
      name: 'pastSurgeries',
      label: 'Past Surgeries',
      type: 'text',
      errorMsg: 'Past Surgeries is required',
      default: 'Appendectomy',
    },
    currentMedications: {
      name: 'currentMedications',
      label: 'Current Medications',
      type: 'text',
      errorMsg: 'Current Medications is required',
      default: 'Ibuprofen',
    },
    allergies: {
      name: 'allergies',
      label: 'Allergies',
      type: 'text',
      errorMsg: 'Allergies is required',
      default: 'None',
    },
    medicalNotes: {
      name: 'medicalNotes',
      label: 'Medical Notes',
      type: 'text',
      errorMsg: 'Medical Notes is required',
      default: 'N/A',
    },
    reasonOfHospitalization: {
      name: 'reasonOfHospitalization',
      label: 'Reason of Hospitalization',
      type: 'text',
      errorMsg: 'Reason of Hospitalization is required',
      default: 'Routine Checkup',
    },
    dateOfAdmission: {
      name: 'dateOfAdmission',
      label: 'Date of Admission',
      type: 'date',
      errorMsg: 'Date of Admission is required',
      default: '2024-07-01',
    },
    dateOfDischarge: {
      name: 'dateOfDischarge',
      label: 'Date of Discharge',
      type: 'date',
      errorMsg: 'Date of Discharge is required',
      default: '2024-07-10',
    },
    lengthOfStay: {
      name: 'lengthOfStay',
      label: 'Length of Stay',
      type: 'text',
      errorMsg: 'Length of Stay is required',
      default: '10 days',
    },
    prcedurePerformed: {
      name: 'prcedurePerformed',
      label: 'Procedure Performed',
      type: 'text',
      errorMsg: 'Procedure Performed is required',
      default: 'None',
    },
    hospitalDischargeSummary: {
      name: 'hospitalDischargeSummary',
      label: 'Hospital Discharge Summary',
      type: 'text',
      errorMsg: 'Hospital Discharge Summary is required',
      default: 'Patient stable',
    },
    followUpInstructions: {
      name: 'followUpInstructions',
      label: 'Follow Up Instructions',
      type: 'text',
      errorMsg: 'Follow Up Instructions is required',
      default: 'Follow up in 6 months',
    },
    diet: {
      name: 'diet',
      label: 'Diet',
      type: 'text',
      errorMsg: 'Diet is required',
      default: 'Balanced diet',
    },
    activityLevel: {
      name: 'activityLevel',
      label: 'Activity Level',
      type: 'text',
      errorMsg: 'Activity Level is required',
      default: 'Moderate',
    },
    exerciseRoutine: {
      name: 'exerciseRoutine',
      label: 'Exercise Routine',
      type: 'text',
      errorMsg: 'Exercise Routine is required',
      default: 'Jogging 3 times a week',
    },
    smokingHabits: {
      name: 'smokingHabits',
      label: 'Smoking Habits',
      type: 'text',
      errorMsg: 'Smoking Habits is required',
      default: 'Non-smoker',
    },
    alcoholConsumption: {
      name: 'alcoholConsumption',
      label: 'Alcohol Consumption',
      type: 'text',
      errorMsg: 'Alcohol Consumption is required',
      default: 'Occasional',
    },
    otherLifestyleFactors: {
      name: 'otherLifestyleFactors',
      label: 'Other Lifestyle Factors',
      type: 'text',
      errorMsg: 'Other Lifestyle Factors is required',
      default: 'None',
    },
  },
};

export default form;
